# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        tpu-type: ["v4-8"]
    name: "TPU test (${{ matrix.tpu-type }})"
    runs-on: ["self-hosted", "tpu", "${{ matrix.tpu-type }}"]
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip3 install virtualenv
        python3 -m virtualenv venv
        source venv/bin/activate
        python3 -m pip install pip==20.0.2
        pip3 install -r requirements.txt -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
        if [ -d flax ] ; then
          rm -rf flax
        fi
        git clone --branch=main https://github.com/google/flax.git
        pip3 install -e flax
    - name: Test with pytest
      run: |
        source venv/bin/activate
        cd MaxText
        python3 -m pytest
